apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlltVnVZV1pzWldNMk1UcG5hSEJmVlV4Q1NreFNaV2RwZGtGSlpVOXRiVWxRUVVabFFUVnpZMFJ1UzNOSE1XNXJTVE5uIgogICAgICAgICAgICAgICAgfQogICAgICAgIH0KfQo=

type: kubernetes.io/dockerconfigjson
